export const TIMER_ALERT_DELIVERY_WINDOW_MS = 5 * 60_000;
export const TIMER_ALERT_DELIVERY_WINDOW_SECONDS =
	TIMER_ALERT_DELIVERY_WINDOW_MS / 1_000;
export const TIMER_TEST_RECEIPT_RETENTION_MS = 30 * 24 * 60 * 60_000;
